### ISSUE TITLE
error generating project with watir

### ISSUE THREAD

**Issue by anadimisra** [cheezy/testgen#14]
```
$ testgen project web-tests-ubiquity --pageobject-driver=watir --with-lib
ERROR: "testgen project" was called with arguments ["web-tests-ubiquity", "--pageobject-driver=watir"]
Usage: "testgen project <project_name>"
```

OS: Mac OSX

**Comment by jmoglesby** [comment]
I hit the same error as @anadimisra  while trying to use the `--pageobject-driver=watir` argument.
Also MacOSX (Catalina)

However, after generating a project without that argument:
`$ testgen project project_name`

I discovered that `testgen` just uses `watir` as its pageobject-driver by default. That argument is no longer needed if using `watir` as your pageobject-driver.

**Comment by anadimisra** [comment]
Sorry for the late response, I reached same conclusion troubleshooting.
